### ISSUE TITLE
lrange third parameter is broken

### ISSUE THREAD

**Issue by jbcrestot** [upstash/redis-js#1111]
Lrange behaviour differs from redis when you pass -1 as the third parameter.

`lrange mykey 0 -1` on redis returns the entire list

while `redis.lrange('elements', 0, -1)` returns the last element of the list
and `redis.lrange('elements', 0, -2)` returns the 2nd last element of the list

**Comment by ogzhanolguncu** [comment]
```
await redis.lpush("foo", 0, 1, 2, 3, 4, 5, 6);
console.log(await redis.lrange("foo", 0, -1));
```

This is giving me -> `[ 6, 5, 4, 3, 2, 1, 0 ]` which is correct? How did you get that results?

**Comment by jbcrestot** [comment]
I have to say that I'm using kv, but they just add some function to redis-js ;

I tried your test, and it's effectively working the same way.

Thank you for the reply, and I am sorry for the inconvenience.

**Comment by ogzhanolguncu** [comment]
No worries. If you have further question you know where to find us. You can also use our [discord](https://discord.com/invite/jUxUYE4nEB)
