### ISSUE TITLE
RediSearch FT.x command not supported?

### ISSUE THREAD

**Issue by officialrobert** [upstash/redis-js#1128]
I wanted to double check if this redis command exists in upstash package https://redis.io/docs/latest/commands/ft.create/

```ts
 await redis.call('FT.INFO', 'key');
```

Please, correct me If I'm wrong incase we don't have plans to support this command.

**Comment by ytkimirti** [comment]
Our redis implementation does not support indexing commands, you can check which commands are supported in our [redis compability page](https://upstash.com/docs/redis/overall/rediscompatibility)

**Comment by Nedi11** [comment]
@ytkimirti Any plans to support redisearch or at least maintain this repo https://github.com/upstash/query
