### ISSUE TITLE
zrange limit

### ISSUE THREAD

**Issue by yuzhen1024** [upstash/redis-js#1212]
hey, how can I do this: ZRANGEBYSCORE your_sorted_set -inf max_score LIMIT 0 10
not found the limit from ZRangeCommandOptions

**Comment by ogzhanolguncu** [comment]
You should use `offset` and `count` 

For example to get only first two:
```
{
        offset: 0,
        count: 2,
},
```

**Comment by yuzhen1024** [comment]
Oh, thank you so much
