### ISSUE TITLE
issue with npm install

### ISSUE THREAD

**Issue by dragonjhlee** [upstash/redis-js#1231]
Hello,
I keep facing the issue with the below error with `npm install` on my local after I run `npm install @upstash/redis` although this error is being bypassed with `yarn install`
```
node_modules/@upstash/redis/zmscore-uDFFyCiZ.d.ts:283:5 - error TS5084: Tuple members must all have names or all not have names.

283     ...TRest
```

Since my code is already set up with `npm` (no issue without this new dependency), it is hard to change everything with `yarn` only for this dependency.
Do you have any clue how to make it work with `npm`?

Thanks!

**Comment by ogzhanolguncu** [comment]
I don't why this happens, but I don't think it's related with the SDK. Maybe clean install would work. Please, remove your lock file and `node_module`, then run `tsc` using your current package manager to check the types in your project.

**Comment by dragonjhlee** [comment]
Hi @ogzhanolguncu 
Okay after I removed the lock file, that issue is resolved.

Thanks for the prompt response.

**Comment by ogzhanolguncu** [comment]
Let us know if you need further help.
