### ISSUE TITLE
hgetall type definition incorrectly returns Record instead of string[]

### ISSUE THREAD

**Issue by taylor-lindores-reeves** [upstash/redis-js#1355]
Possibly a bug in the `@upstash/redis` type definitions. Let me break it down:

The type definition says:

`hgetall: <Record<string, unknown>>(key: string) => Promise<Record<string, unknown> | null>`

But the actual return value is:

`const result: string[] // an array of strings`

This is a mismatch between the type definition from `hgetall` and the actual implementation. It appears that:

- The Redis protocol returns hash fields and values as a flat array
- @upstash/redis keeps the array format but incorrectly types it as a Record

**Comment by CahidArda** [comment]
Hi there,

I just checked the `@upstash/redis` implementation and tried to run HGETALL myself. HGETALL in `@upstash/redis` returns an object instead of a list. In Redis protocol, it's a list like you said.

In other words, what's returned in `@upstash/redis` and its type definition should be correct. It's just not compatible with Redis protocol.

I see that this can be unexpected, but `@upstash/redis` written this way to make it more convenient.

**Comment by taylor-lindores-reeves** [comment]
> Hi there,
> 
> I just checked the `@upstash/redis` implementation and tried to run HGETALL myself. HGETALL in `@upstash/redis` returns an object instead of a list. In Redis protocol, it's a list like you said.
> 
> In other words, what's returned in `@upstash/redis` and its type definition should be correct. It's just not compatible with Redis protocol.
> 
> I see that this can be unexpected, but `@upstash/redis` written this way to make it more convenient.

Thanks for the quick response, please can you let me know what could be causing the incorrect return type? Why are we getting the raw array format instead of the transformed object?

**Comment by CahidArda** [comment]
which version of @upstash/redis are your using?

**Comment by taylor-lindores-reeves** [comment]
> @upstash/redis

^1.34.3

**Comment by CahidArda** [comment]
Only way I can see is if a custom deserializer is passed, and looking at the code it look like this isn't allowed. Can you share a code snippet showing how you initialize redis and call hgetall which results in this behavior?

**Comment by taylor-lindores-reeves** [comment]
// redis.ts

```
import { Redis } from "@upstash/redis";

// Initialize the client
const redis = Redis.fromEnv({ automaticDeserialization: true });

export { redis };

```

// set and usage

`await redis.hset(`sessions:${user.id}:${deviceKey}`, deviceInfo);`

```
export async function getDevice(userId: string, deviceId: string) {
	return redis.hgetall<DeviceType>(`sessions:${userId}:device:${deviceId}`);
}
```

**Comment by CahidArda** [comment]
The problem is fixed then.

Looking at the code, I see that you utilize `automaticDeserialization`. If that's set to false, then you will get a raw array.

Perhaps you had set it to false unintentionally. Default value is true.

**Comment by taylor-lindores-reeves** [comment]
Okay, makes sense, thanks for the help.
