### ISSUE TITLE
Support for passing an abort signal to the underlying fetch requests

### ISSUE THREAD

**Issue by SamyPesse** [upstash/redis-js#778]
I have an use case where I use upstash in a Cloudflare Worker to concurently try multiple cache keys and stop at the first one. But Cloudflare crashes the request if there are pending tasks when a response is generated (see https://zuplo.com/blog/2022/03/04/the-script-will-never-generate-a-response).

The solution is to correctly cancel all inflight requests before returning a response, to do so I need to able to pass a `signal` ([`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)) to the underlying fetch call.

It'd be great if each upstash function had a last option argument to pass one 🙏

**Comment by SamyPesse** [comment]
Or a way to pass a custom fetch (https://github.com/upstash/upstash-redis/blob/main/pkg/http.ts#L187) function in the constructor will be a good workaround

**Comment by ogzhanolguncu** [comment]
To be honest both options are great addition. So, I'll take a look at this and let you know soon.

**Comment by ogzhanolguncu** [comment]
@SamyPesse I've made a PR, but first I wanted to make sure we are on the same page. Can you please check this PR out and see if it actually helps you [Signal](https://github.com/upstash/upstash-redis/pull/783/files#diff-8ddd7ea4952c6b282a593053c2dd70182e035a6ed7eea75127d379a58878283c). If so I need to add this config to every command we have.

**Comment by SamyPesse** [comment]
I took a look at https://github.com/upstash/upstash-redis/pull/783 and this is exactly what we are looking for 👍

**Comment by ogzhanolguncu** [comment]
I feel passing a signal to each command will too much to maintain. I'll add a ability to pass a custom fetch as we spoke earlier. Let you know soon.

**Comment by ogzhanolguncu** [comment]
@SamyPesse I believe I found the middle ground by instantiating new clients with signal. I've also tested it with CF and Node, and it works. Aborted commands will return `null`.

https://github.com/upstash/upstash-redis/pull/786 


```typescript
export default {
  async fetch(
    _request: Request,
    env: Env,
    _ctx: ExecutionContext
  ): Promise<Response> {
    const controller = new AbortController();
    const redis = Redis.fromEnv(env, { signal: controller.signal });
    const redis1 = Redis.fromEnv(env);

    controller.abort();
    const count = await redis.incr("cloudflare-workers-with-typescript-count");
    const count1 = await redis1.incr(
      "cloudflare-workers-with-typescript-count"
    );

    return new Response(JSON.stringify({ count: count ?? "Aborted", count1 }));
  },
};
```

**Comment by SamyPesse** [comment]
Having a signal at the client level will not be great for us (client is defined as a global variable), but we'll make it work, it's better than not having it :)

**Comment by ogzhanolguncu** [comment]
Once we have the resources i'll plan to add command level signals, don't worry.

**Comment by ogzhanolguncu** [comment]
bump

**Comment by matsuby** [comment]
@ogzhanolguncu @SamyPesse 
> Having a signal at the client level will not be great for us (client is defined as a global variable), but we'll make it work, it's better than not having it :)

I made PR #957, I introduce `timeout` option instead `signal`.
Please review it.

**Comment by BitPhinix** [comment]
Bump on command level signals

**Comment by BitPhinix** [comment]
Digging through the code, it seems like this is already supported, although not exposed on typing level via

```ts
this.abortController = new AbortController()

await this.redis.xread(
  Array.from(this.subscriptionStates.keys()),
  Array.from(this.subscriptionStates.values()),
  {
    blockMS: 60_000,
    streamOptions: { signal: this.abortController.signal },
  },
)
```
